### ISSUE TITLE
RCT Configuration

### ISSUE THREAD

**Issue by dabadav** [dabadav/ai-cdss#2]
### Tasks:
- [x] T1. Define clinical subscales used in the RCT with `max_values` and possible `aliases`
- [x] T2. Define mapping between clinical subscales 
- [ ] T3. Complete Protocol Attributes matrix of missing protocols (@Anna)

#### T1. Modify config/scales.yaml
```yaml
data:
  ACT_AU: 10
  ACT_QOM: 10
  ASH_PROXIMAL: 4
  BARTHEL: 100
  FATIGUE: 63
  FM_A: 36
  FM_B: 10
  FM_C: 14
  FM_D: 6
  FM_TOTAL: 66
  MA_DISTAL: 4
  VAS: 10
keys:
  BARTHEL:
  - Barthel Index
  - BI
  VAS:
  - Visual Analog Scale
 ...
``` 

#### T2. Modify config/mapping.yaml
```yaml
data:
  # Functional Independence
  BARTHEL:
    - DAILY_LIVING_ACTIVITY  # Barthel Index measures independence in ADLs.

  # Motor Function (Spasticity & Strength)
  ASH_PROXIMAL:
    - BODY_PART_ARM
    - BODY_PART_SHOULDER
    - COORDINATION  # Ashworth scale for proximal limb spasticity.

  MA_DISTAL:
    - BODY_PART_FINGER
    - BODY_PART_WRIST
    - GRASPING
    - PINCHING  # Motor Assessment for distal motor function.

  # Fatigue & Pain
  FATIGUE:
    - DIFFICULTY_COGNITIVE
    - DIFFICULTY_MOTOR
    - PROCESSING_SPEED
    - ATTENTION  # Fatigue relates to cognitive/motor difficulty.
  ...
``` 

### T3. Missing protocols in Protocol Matrix of Attributes

**Mind protocol aliases for:
- (225) Do the dishes (AR) --> Cleaning-H (AR), 
- (227) Canvas wiping (AR) --> Cleaning-V (AR)

- [x] Fill Missing Protocols: **[218] Spheroids (AR)**, [207] Football AR, [234] Falling Objects
- [x] Fill Missing Attributes in Protocols
